# Generated by Django 3.2.4 on 2021-06-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.TextField(primary_key=True, serialize=False)),
                ('received', models.FloatField()),
                ('send', models.FloatField()),
                ('balance', models.FloatField()),
                ('numtransactions', models.IntegerField()),
                ('json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nexthash', models.CharField(max_length=64)),
                ('prevhash', models.CharField(max_length=64)),
                ('numtransactions', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('merkleroot', models.TextField()),
                ('minedby', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('difficulty', models.FloatField()),
                ('size', models.PositiveIntegerField()),
                ('nonce', models.PositiveBigIntegerField()),
                ('version', models.PositiveBigIntegerField()),
                ('bits', models.PositiveBigIntegerField()),
                ('netexchanged', models.FloatField()),
                ('json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('coinbase', models.BooleanField()),
                ('addressmap', models.JSONField()),
                ('size', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('netexchanged', models.FloatField()),
                ('confirmations', models.IntegerField()),
                ('json', models.JSONField()),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.block')),
                ('inputaddresses', models.ManyToManyField(related_name='transactionswhereinput', to='backend.Address')),
                ('inputtxids', models.ManyToManyField(related_name='transactionswhereinput', to='backend.Transaction')),
                ('outputaddresses', models.ManyToManyField(related_name='transactionswhereoutput', to='backend.Address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='transactions',
            field=models.ManyToManyField(related_name='addresses', to='backend.Transaction'),
        ),
    ]
