# Generated by Django 3.2.4 on 2021-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210630_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='bits',
            field=models.TextField(null=True),
        ),
    ]
