# Generated by Django 3.2.4 on 2021-07-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_transaction_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='inputtxids',
        ),
    ]
