# Generated by Django 3.2.4 on 2021-07-02 00:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_transaction_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='transactions',
        ),
        migrations.AddField(
            model_name='address',
            name='transactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
    ]
